---
- name: Setup
  hosts: all
  remote_user: deployer
  vars_files:
    - vars/setup.yml
    - vars/secrets.yml
  roles:
    - common
    - setupSSH
    - packages
    - shell
    - unattended-upgrades
    - role: swap
      tags: ['swap']
  handlers:
    - include: handlers.yml

- name: Setup Docker
  hosts: docker
  remote_user: deployer
  roles:
    - role: docker
      tags: ['docker']

- name: Configure Borg backup
  hosts: borgbackup
  become: true
  roles:
    - role: borgbase.ansible_role_borgbackup
      tags: ['backup']

- name: Setup Development
  hosts: development
  remote_user: deployer
  roles:
    - role: development
      tags: ['development']

- name: Setup Monitoring
  hosts: monitoring
  remote_user: deployer
  roles:
    - role: monitoring
      tags: ['monitoring']

- name: Setup Tailscale
  hosts: tailscale
  remote_user: deployer
  roles:
    - role: tailscale
      tags: ['tailscale']
