- name: Setup Unattended-Upgrades
  ansible.builtin.include_role:
    name: hifis.unattended_upgrades
    apply:
      tags:
        - unattended-upgrades

  vars:
    ansible_become: true
    unattended_automatic_reboot: yes
    unattended_automatic_reboot_time: 03:00

  tags:
    - unattended-upgrades
