- name: Add Docker GPG key
  become: yes
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install Docker with dependencies
  package:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - python3-pip
  become: yes

- name: Install python dependencies
  become: yes
  pip:
    name: docker-py
    state: latest

- name: Add deployer to docker group
  become: yes
  user:
    name: deployer
    groups: docker
    state: present
    append: yes

- name: Deploy Docker daemon.json.
  become: yes
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Create a docker directory
  become: yes
  file:
    path: /docker
    owner: deployer
    group: deployer
    state: directory

- name: Add docker cleanup cronjob
  become: yes
  ansible.builtin.cron:
    name: "docker cleanup"
    minute: "0"
    hour: "23"
    weekday: "0" # Sunday
    user: root
    job: "docker system prune --force > /dev/null"
    cron_file: docker

- name: Get path of leagcy docker-compose
  command: which docker-compose
  register: docker_compose_path
  ignore_errors: yes

- name: Delete legacy docker-compose
  become: yes
  ansible.builtin.file:
    path: '{{ docker_compose_path.stdout }}'
    state: absent
  when: docker_compose_path.rc == 0
